# Importação de Arquivo HTML - Estudos part4 Séries Temporais

In [1]:
import pandas as pd
import html5lib

In [2]:
df = pd.read_html('https://pt.wikipedia.org/wiki/Unidades_federativas_do_Brasil')

In [4]:
type(df)

list

In [6]:
df[1]

,Bandeira,Unidade federativa,Abreviação,Sede de governo,Área (km²),População (2014),Densidade (2005),PIB (2015),(% total) (2015),PIB per capita (R$) (2015),IDH (2010),Alfabetização (2016),Mortalidade infantil (2016),Expectativa de vida (2016)
0,NaN,Acre,AC,Rio Branco,"164 122,2",795 145,430,13 622 000,2,"16 953,46",663,"86,9%","17,0‰","73,9 anos"
1,NaN,Alagoas,AL,Maceió,"27 767,7",3 327 551,10861,46 364 000,8,"13 877,53",631,"80,6%","19,5‰","71,6 anos"
2,NaN,Amapá,AP,Macapá,"142 814,6",756 500,416,13 861 000,2,"18 079,54",708,95%,"23,2‰","73,9 anos"
3,NaN,Amazonas,AM,Manaus,"1 570 745,7",3 893 763,205,86 560 000,14,"21 978,95",674,"93,1%","18,2‰","71,9 anos"
4,NaN,Bahia,BA,Salvador,"564 692,7",15 150 143,2446,245 025 000,41,"16 115,89",660,87%,"17,3‰","73,5 anos"
5,NaN,Ceará,CE,Fortaleza,"148 825,6",8 867 448,5440,130 621 000,22,"14 669,14",682,"84,8%","14,4‰","73,8 anos"
6,NaN,Distrito Federal,DF,Brasília,"5 822,1",2 867 869,40073,215 613 000,36,"73 971,05",824,"97,4%","10,5‰","78,1 anos"
7,NaN,Espírito Santo,ES,Vitória,"46 077,5",3 894 899,7397,120 363 000,2,"30 627,45",740,"93,8%","8,8‰","78,2 anos"
8,NaN,Goiás,GO,Goiânia,"340 086,7",6 551 322,1652,173 632 000,29,"26 265,32",735,"93,5%","14,9‰","74,2 anos"
9,NaN,Maranhão,MA,São Luís,"331 983,3",6 861 924,1838,78 475 000,13,"11 366,23",639,"83,3%","21,3‰","70,6 anos"
10,NaN,Mato Grosso,MT,Cuiabá,"903 357,9",3 236 578,310,107 418 000,18,"32 894,96",725,"93,5%","16,9‰","74,2 anos"
11,NaN,Mato Grosso do Sul,MS,Campo Grande,"357 125,0",2 630 098,634,83 082 000,14,"31 337,22",729,"93,7%","14,0‰","75,5 anos"
12,NaN,Minas Gerais,MG,Belo Horizonte,"586 528,3",20 777 672,3279,519 326 000,87,"24 884,94",731,"93,8%","10,9‰","77,2 anos"
13,NaN,Pará,PA,Belém,"1 247 689,5",8 101 180,558,130 883 000,22,"16 009,98",646,"90,7%","16,6‰","72,1 anos"
14,NaN,Paraíba,PB,João Pessoa,"56 439,8",3 950 359,6371,56 140 000,9,"14 133,32",658,"83,7%","16,1‰","73,2 anos"
15,NaN,Paraná,PR,Curitiba,"199 314,9",11 112 062,5148,376 960 000,63,"33 768,62",749,"95,5%","9,3‰","77,1 anos"
16,NaN,Pernambuco,PE,Recife,"98 311,6",9 297 861,8558,156 955 000,26,"16 795,34",673,"87,2%","12,7‰","73,9 anos"
17,NaN,Piauí,PI,Teresina,"251 529,2",3 198 185,1195,39 148 000,7,"12 218,51",646,"82,8%","19,1‰","71,1 anos"
18,NaN,Rio de Janeiro,RJ,Rio de Janeiro,"43 696,1",16 497 395,35205,659 137 000,11,"39 826,95",761,"97,3%","11,5‰","76,2 anos"
19,NaN,Rio Grande do Norte,RN,Natal,"52 796,8",3 419 550,5688,57 250 000,1,"16 631,86",684,"85,3%","14,7‰","75,7 anos"
20,NaN,Rio Grande do Sul,RS,Porto Alegre,"281 748,5",11 228 091,3849,381 985 000,64,"33 960,36",746,"96,8%","9,6‰","77,8 anos"
21,NaN,Rondônia,RO,Porto Velho,"237 576,2",1 755 015,646,36 563 000,6,"20 677,95",690,"93,3%","20,0‰","71,3 anos"
22,NaN,Roraima,RR,Boa Vista,"224 299,0",500 826,174,10 354 000,2,"20 476,71",707,"93,4%","17,2‰","71,5 anos"
23,NaN,Santa Catarina,SC,Florianópolis,"95 346,2",6 734 568,6153,249 073 000,42,"36 525,28",774,"97,2%","9,2‰","79,1 anos"
24,NaN,São Paulo,SP,São Paulo,"248 209,4",44 169 350,16293,1 939 890 000,324,"43 694,68",783,"97,2%","9,9‰","78,1 anos"
25,NaN,Sergipe,SE,Aracaju,"21 910,3",2 227 294,8981,38 554 000,6,"17 189,28",665,"85,3%","16,2‰","72,7 anos"
26,NaN,Tocantins,TO,Palmas,"277 620,9",1 502 759,470,28 930 000,5,"19 094,16",699,"89,6%","15,8‰","73,4 anos"

In [7]:
df2 = pd.read_html('https://pt.wikipedia.org/wiki/Lista_dos_maiores_bancos_do_Brasil')

In [9]:
df2[1]

,Posição,Nome do banco,Cidade sede,Ativos totais em R$ (bilhões),Data dos dados,País de origem
0,1,Itaú Unibanco,São Paulo,1.739[1],Dezembro de 2019,Brasil
1,2,Banco de Brasília,Brasília,1.540[2],Dezembro de 2019,Brasil
2,3,Caixa Econômica Federal,Brasília,1.293[3],Dezembro de 2019,Brasil
3,4,Bradesco,Osasco,1.152[4],Dezembro de 2019,Brasil
4,5,Santander Brasil,São Paulo,"839,8[5]",Dezembro de 2019,Espanha
5,6,BTG Pactual,São Paulo,"176,6[6]",Dezembro de 2019,Brasil
6,7,Banco Safra,São Paulo,"167,5[7]",Dezembro de 2019,Brasil
7,8,Sicoob,Brasília,"117,2[6]",Dezembro de 2019,Brasil
8,9,Banco Votorantim,São Paulo,"88,8[8]",Dezembro de 2019,Brasil
9,10,Citibank Brasil,São Paulo,"88,5[9]",Dezembro de 2019,Estados Unidos
10,11,Banrisul,Porto Alegre,"80,9[10]",Dezembro de 2019,Brasil
11,12,Banco do Nordeste,Fortaleza,"58,6[11]",Dezembro de 2019,Brasil